/**
 * Wszystkie teksty interfejsu DJ-a. Żaden tekst nie jest wpisany na sztywno w komponencie
 * (AGENTS.md, konwencje frontendu). Aplikacja jest po polsku.
 */
export const ui = {
  appName: "ANON DJ",
  window: {
    minimize: "Zminimalizuj",
    close: "Zamknij",
  },
  status: {
    player: "Odtwarzacz",
    playerUnknown: "nie sprawdzono",
    playerUnavailable: "brak połączenia",
    playerPlaying: "gra",
    playerPaused: "pauza",
    playerStopped: "nie gra",
    kiosk: "Kiosk",
    kioskDisconnected: "rozłączony",
    server: "Serwer",
    serverUnavailable: "nie nasłuchuje",
    serverUnknownAddress: "adres nieznany",
    loading: "Wczytywanie…",
    errorPrefix: "Błąd",
  },
  requests: {
    loadError: "Nie udało się wczytać kolejki:",
  },
  queue: {
    reviewTitle: "Do przeglądu",
    reviewHint:
      "Dedykacje od gości. Popraw, zatwierdź albo odrzuć — nic nie poleci bez Twojej decyzji.",
    reviewEmpty: "Brak dedykacji czekających na przegląd.",
    readyTitle: "Gotowe do wykonania",
    readyHint: "Zatwierdzone dedykacje. Ustaw kolejność, w jakiej pójdą na antenę.",
    readyEmpty: "Nic nie czeka na wykonanie.",
    historyTitle: "Historia",
    historyHint: "Dedykacje już na antenie, wykonane i odrzucone.",
    historyEmpty: "Historia jest pusta.",
    approve: "Zatwierdź",
    reject: "Odrzuć",
    edit: "Popraw",
    saveEdit: "Zapisz",
    cancelEdit: "Anuluj",
    moveUp: "W górę",
    moveDown: "W dół",
    charsLabel: "znaków",
    approveError: "Nie udało się zatwierdzić dedykacji:",
    rejectError: "Nie udało się odrzucić dedykacji:",
    editError: "Nie udało się zapisać poprawki:",
    moveError: "Nie udało się przesunąć dedykacji:",
    execute: "Wykonaj",
    executing: "Wykonuję…",
    executeError: "Nie udało się wykonać dedykacji:",
    // Voice-over: stan przygotowania klipu lektora (PLAN.md, sekcja 8).
    voiceOver: {
      generating: "Generuję voice-over…",
      ready: "Voice-over gotowy",
      failed: "Nie udało się przygotować voice-overu:",
      missing: "Voice-over nieprzygotowany",
      generate: "Przygotuj voice-over",
      retry: "Spróbuj ponownie",
      unavailable: "Lektor niedostępny — przeczytaj dedykację z ekranu.",
      generateError: "Nie udało się zamówić voice-overu:",
      percentSuffix: "%",
      play: "Odsłuchaj",
      stop: "Zatrzymaj",
      playError: "Nie udało się odtworzyć voice-overu:",
      stopError: "Nie udało się zatrzymać odtwarzania:",
    },
    // Podpisy statusów prośby — pokazujemy je słowem, nie kodem.
    statuses: {
      submitted: "Czeka na przegląd",
      approved: "Zatwierdzona",
      playing: "W trakcie",
      done: "Wykonana",
      rejected: "Odrzucona",
    },
  },
  nav: {
    queues: "Kolejki",
    library: "Biblioteka",
    voice: "Lektor",
    settings: "Ustawienia",
  },
  voice: {
    title: "Lektor dedykacji",
    hint: "Zmiany zapisujesz przyciskiem u dołu — do tego czasu możesz spokojnie porównywać głosy.",
    unavailable: "Lektor jest niedostępny — dedykacje trzeba przeczytać z ekranu:",
    voicesTitle: "Głos",
    voicesEmpty: "Nie znaleziono żadnego zainstalowanego głosu.",
    voicesError: "Nie udało się wczytać listy głosów:",
    activeTag: "czyta teraz",
    licenseLabel: "licencja",
    quality: {
      low: "niska jakość",
      medium: "średnia jakość",
      high: "wysoka jakość",
      unknown: "jakość nieznana",
    },
    tuningTitle: "Strojenie",
    // Suwaki. Podpis wartości mówi, co się stanie z mową, a nie jak nazywa się parametr silnika.
    // W prawo zawsze znaczy „więcej tego, co w podpisie” — kolejność odwrotna panowała tylko
    // przy tempie i tylko dlatego, że silnik trzyma je jako długość, nie szybkość.
    tempoLabel: "Tempo mowy",
    tempoHint: "W prawo szybciej. Sto procent to tempo, w jakim głos mówi domyślnie.",
    noiseLabel: "Barwa głosu",
    noiseHint: "W prawo brzmi żywiej, w lewo bardziej monotonnie.",
    noiseWLabel: "Rytm mowy",
    noiseWHint: "W prawo pauzy i akcenty są bardziej zmienne.",
    volumeLabel: "Głośność lektora",
    volumeHint: "Głośność wobec muzyki. Sto procent to poziom z nagrania.",
    silenceLabel: "Pauza między zdaniami",
    silenceHint: "W prawo dłuższa pauza. Krótka trzyma dedykację w kupie, długa daje jej oddech.",
    previewTitle: "Próbka",
    previewText: "Dobry wieczór! Dla Kasi i Marka — sto lat i samych udanych imprez.",
    previewSuffixNotice: "Ten tekst przeczyta lektor na próbce.",
    previewPlay: "Odsłuchaj próbkę",
    previewStop: "Zatrzymaj",
    previewBusy: "Generuję próbkę…",
    previewError: "Nie udało się przygotować próbki:",
    previewStopError: "Nie udało się zatrzymać próbki:",
    previewTook: "synteza",
    previewLength: "nagranie",
    reset: "Przywróć domyślne",
    resetHint: "Wraca do domyślnego głosu i jego strojenia. Zapisujesz dopiero przyciskiem obok.",
    resetError: "Nie udało się wczytać domyślnych ustawień lektora:",
    save: "Zapisz głos",
    saving: "Zapisywanie…",
    saved: "Zapisano",
    saveError: "Nie udało się zapisać ustawień lektora:",
    loadError: "Nie udało się wczytać ustawień lektora.",
  },
  settings: {
    title: "Ustawienia",
    hint: "Obowiązują od razu po zapisaniu, a zapis zamyka to okno. Zamknięcie bez zapisu niczego nie zmienia.",
    close: "Zamknij",
    connectionTitle: "Połączenie i kiosk",
    limitsTitle: "Limity tekstów",
    audioTitle: "Dźwięk",
    pinLabel: "PIN parowania kiosku",
    pinHint: "Dokładnie sześć cyfr. Kiosk podaje ten kod przy łączeniu.",
    portLabel: "Port serwera kiosków",
    portHint: "Ten sam port wpisujesz w kiosku — razem z adresem z paska statusu.",
    confirmationSecondsLabel: "Powrót ekranu potwierdzenia (sekundy)",
    confirmationSecondsHint: "Po ilu sekundach kiosk sam wróci do szukania, żeby kolejny gość mógł pisać. Ten czas dostaje kiosk przy parowaniu.",
    confirmationSecondsError: "Czas musi być liczbą z zakresu 5–300 sekund.",
    audioDeviceLabel: "Wyjście na antenę",
    audioDeviceHint: "Tędy idzie voice-over razem z muzyką, więc musi to być to samo wyjście co utwór — inaczej gość usłyszy lektora z innych głośników.",
    audioDeviceDefault: "Domyślne urządzenie systemowe",
    audioDeviceDefaultTag: "domyślne",
    audioDeviceMissing: "Wybrane urządzenie jest teraz niepodłączone",
    audioDeviceError: "Nie udało się wczytać listy urządzeń:",
    auditionDeviceLabel: "Odsłuch dedykacji (DJ)",
    auditionDeviceHint: "Tutaj sprawdzasz dedykację przed zatwierdzeniem. Wskaż słuchawki, żeby nie puszczać odsłuchu na salę.",
    auditionDeviceSameAsOutput: "Jak na antenie",
    sequenceTitle: "Sekwencja wykonania",
    sequenceHint: "Jak muzyka zachowuje się pod lektorem w trakcie wykonania. Odsłuch z kolejki tego nie używa.",
    duckLevelLabel: "Ściszenie pod lektorem (%)",
    duckLevelHint: "Na jaką część głośności zejść, kiedy mówi lektor. Sto procent to brak ściszenia.",
    duckRampLabel: "Czas ściszania (ms)",
    duckRampHint: "Jak płynnie zejść do poziomu ściszenia.",
    gapLabel: "Pauza po dedykacji (ms)",
    gapHint: "Chwila oddechu, zanim stary utwór zacznie znikać.",
    fadeOutLabel: "Wyciszenie starego utworu (ms)",
    fadeOutHint: "Jak długo stary utwór schodzi do zera, zanim wejdzie zamówiony.",
    startRampLabel: "Wejście zamówionego utworu (ms)",
    startRampHint: "Jak długo zamówiony utwór wjeżdża do normalnej głośności.",
    sequenceNumberError: "Podaj liczbę z dozwolonego zakresu.",
    dedicationLimitLabel: "Limit dedykacji (znaki)",
    dedicationLimitHint: "Ile znaków może wpisać gość. Ten sam limit dostaje kiosk przy parowaniu.",
    guestNameLimitLabel: "Limit imienia gościa (znaki)",
    guestNameLimitHint: "Zero wyłącza pole imienia.",
    searchQueryLimitLabel: "Limit wyszukiwania (znaki)",
    save: "Zapisz",
    saving: "Zapisywanie…",
    loadError: "Nie udało się wczytać ustawień.",
    numberError: "Podaj poprawną liczbę.",
    portError: "Port musi być liczbą z zakresu 1024–65535.",
  },
  library: {
    title: "Biblioteka",
    hint: "Wskaż foldery z muzyką i uruchom skanowanie. Zapisujemy tylko metadane i ścieżki — pliki zostają na swoim miejscu.",
    foldersTitle: "Foldery z muzyką",
    foldersHint: "Usunięcie folderu zabiera z biblioteki także jego utwory.",
    foldersEmpty: "Nie wskazano jeszcze żadnego folderu.",
    addFolder: "Dodaj folder",
    removeFolder: "Usuń folder",
    scan: "Skanuj bibliotekę",
    scanRunning: "Skanowanie…",
    statsFolders: "Foldery",
    statsTracks: "Utwory",
    progressFolder: "folder",
    progressFiles: "plików",
    progressIndexed: "dodanych",
    progressSkipped: "pominiętych",
    searchLabel: "Szukaj w bibliotece",
    searchPlaceholder: "Tytuł albo wykonawca…",
    searchEmpty: "Nic nie pasuje do tego wyszukiwania.",
    libraryEmpty: "Biblioteka jest pusta — dodaj folder z muzyką i uruchom skanowanie.",
    unknownArtist: "Nieznany wykonawca",
    unknownAlbum: "bez albumu",
    noDuration: "—",
    loadError: "Nie udało się wczytać biblioteki:",
    addError: "Nie udało się dodać folderu:",
    removeError: "Nie udało się usunąć folderu:",
    scanError: "Nie udało się uruchomić skanowania:",
    searchError: "Nie udało się wyszukać:",
  },
  footer: {
    version: "Wersja",
    protocol: "Protokół",
    db: "Baza",
    logs: "Logi",
  },
} as const;
