/**
 * Wszystkie teksty interfejsu DJ-a. Żaden tekst nie jest wpisany na sztywno w komponencie
 * (AGENTS.md, konwencje frontendu). Aplikacja jest po polsku.
 */
export const ui = {
  appName: "ANON DJ",
  window: {
    minimize: "Zminimalizuj",
    close: "Zamknij",
  },
  status: {
    player: "Odtwarzacz",
    playerUnknown: "nie sprawdzono",
    kiosk: "Kiosk",
    kioskDisconnected: "rozłączony",
    server: "Serwer",
    serverUnavailable: "nie nasłuchuje",
    serverUnknownAddress: "adres nieznany",
    loading: "Wczytywanie…",
    errorPrefix: "Błąd",
  },
  requests: {
    loadError: "Nie udało się wczytać kolejki:",
  },
  queue: {
    reviewTitle: "Do przeglądu",
    reviewHint:
      "Dedykacje od gości. Popraw, zatwierdź albo odrzuć — nic nie poleci bez Twojej decyzji.",
    reviewEmpty: "Brak dedykacji czekających na przegląd.",
    readyTitle: "Gotowe do wykonania",
    readyHint: "Zatwierdzone dedykacje. Ustaw kolejność, w jakiej pójdą na antenę.",
    readyEmpty: "Nic nie czeka na wykonanie.",
    historyTitle: "Historia",
    historyHint: "Wykonane i odrzucone dedykacje.",
    historyEmpty: "Historia jest pusta.",
    approve: "Zatwierdź",
    reject: "Odrzuć",
    edit: "Popraw",
    saveEdit: "Zapisz",
    cancelEdit: "Anuluj",
    moveUp: "W górę",
    moveDown: "W dół",
    charsLabel: "znaków",
    approveError: "Nie udało się zatwierdzić dedykacji:",
    rejectError: "Nie udało się odrzucić dedykacji:",
    editError: "Nie udało się zapisać poprawki:",
    moveError: "Nie udało się przesunąć dedykacji:",
    // Voice-over: stan przygotowania klipu lektora (PLAN.md, sekcja 8).
    voiceOver: {
      generating: "Generuję voice-over…",
      ready: "Voice-over gotowy",
      failed: "Nie udało się przygotować voice-overu:",
      missing: "Voice-over nieprzygotowany",
      generate: "Przygotuj voice-over",
      retry: "Spróbuj ponownie",
      unavailable: "Lektor niedostępny — przeczytaj dedykację z ekranu.",
      generateError: "Nie udało się zamówić voice-overu:",
      percentSuffix: "%",
      play: "Odsłuchaj",
      stop: "Zatrzymaj",
      playError: "Nie udało się odtworzyć voice-overu:",
      stopError: "Nie udało się zatrzymać odtwarzania:",
    },
    // Podpisy statusów prośby — pokazujemy je słowem, nie kodem.
    statuses: {
      submitted: "Czeka na przegląd",
      approved: "Zatwierdzona",
      playing: "W trakcie",
      done: "Wykonana",
      rejected: "Odrzucona",
    },
  },
  nav: {
    queues: "Kolejki",
    library: "Biblioteka",
    voice: "Lektor",
    settings: "Ustawienia",
  },
  voice: {
    title: "Lektor dedykacji",
    hint: "Wybierz głos i posłuchaj próbki. Zmiany zapisują się dopiero przyciskiem Zapisz — do tego czasu możesz porównywać do woli.",
    unavailable: "Lektor jest niedostępny — dedykacje trzeba przeczytać z ekranu:",
    voicesTitle: "Głos",
    voicesEmpty: "Nie znaleziono żadnego zainstalowanego głosu.",
    voicesError: "Nie udało się wczytać listy głosów:",
    activeTag: "czyta teraz",
    licenseLabel: "licencja",
    quality: {
      low: "niska jakość",
      medium: "średnia jakość",
      high: "wysoka jakość",
      unknown: "jakość nieznana",
    },
    tuningTitle: "Strojenie",
    // Suwaki. Podpis wartości mówi, co się stanie z mową, a nie jak nazywa się parametr silnika.
    tempoLabel: "Tempo mowy",
    tempoHint: "Więcej = wolniej. Za szybko i goście nie zrozumieją imion, za wolno — dedykacja nie zmieści się w utworze.",
    noiseLabel: "Barwa głosu",
    noiseHint: "Wyżej brzmi żywiej, niżej bardziej monotonnie.",
    noiseWLabel: "Rytm mowy",
    noiseWHint: "Wyżej pauzy i akcenty są bardziej zmienne.",
    volumeLabel: "Głośność lektora",
    volumeHint: "Głośność wobec muzyki. Sto procent to poziom z nagrania.",
    silenceLabel: "Pauza między zdaniami",
    silenceHint: "Krótka pauza trzyma dedykację w kupie, długa daje jej oddech.",
    previewTitle: "Próbka",
    previewText: "Dobry wieczór! Dla Kasi i Marka — sto lat i samych udanych imprez.",
    previewSuffixNotice: "Ten tekst przeczyta lektor na próbce.",
    previewPlay: "Odsłuchaj próbkę",
    previewStop: "Zatrzymaj",
    previewBusy: "Generuję próbkę…",
    previewError: "Nie udało się przygotować próbki:",
    previewStopError: "Nie udało się zatrzymać próbki:",
    previewTook: "synteza",
    previewLength: "nagranie",
    save: "Zapisz głos",
    saving: "Zapisywanie…",
    saved: "Zapisano",
    saveError: "Nie udało się zapisać ustawień lektora:",
    loadError: "Nie udało się wczytać ustawień lektora.",
  },
  settings: {
    title: "Ustawienia",
    hint: "Wszystkie wartości zapisują się w bazie i obowiązują od razu po zapisaniu.",
    pinLabel: "PIN parowania kiosku",
    pinHint: "Dokładnie sześć cyfr. Kiosk podaje ten kod przy łączeniu.",
    portLabel: "Port serwera kiosków",
    portHint: "Ten sam port wpisujesz w kiosku — razem z adresem z paska statusu.",
    confirmationSecondsLabel: "Powrót ekranu potwierdzenia (sekundy)",
    confirmationSecondsHint: "Po ilu sekundach kiosk sam wróci do szukania, żeby kolejny gość mógł pisać. Ten czas dostaje kiosk przy parowaniu.",
    confirmationSecondsError: "Czas musi być liczbą z zakresu 5–300 sekund.",
    audioDeviceLabel: "Urządzenie wyjściowe voice-overu",
    audioDeviceHint: "Voice-over musi wyjść tym samym wyjściem co muzyka — inaczej gość usłyszy lektora z innych głośników niż utwór.",
    audioDeviceDefault: "Domyślne urządzenie systemowe",
    audioDeviceDefaultTag: "domyślne",
    audioDeviceMissing: "Wybrane urządzenie jest teraz niepodłączone",
    audioDeviceError: "Nie udało się wczytać listy urządzeń:",
    dedicationLimitLabel: "Limit dedykacji (znaki)",
    dedicationLimitHint: "Ile znaków może wpisać gość. Ten sam limit dostaje kiosk przy parowaniu.",
    guestNameLimitLabel: "Limit imienia gościa (znaki)",
    guestNameLimitHint: "Zero wyłącza pole imienia.",
    searchQueryLimitLabel: "Limit wyszukiwania (znaki)",
    save: "Zapisz",
    saving: "Zapisywanie…",
    saved: "Zapisano",
    loadError: "Nie udało się wczytać ustawień.",
    numberError: "Podaj poprawną liczbę.",
    portError: "Port musi być liczbą z zakresu 1024–65535.",
  },
  library: {
    title: "Biblioteka",
    hint: "Wskaż foldery z muzyką i uruchom skanowanie. Zapisujemy tylko metadane i ścieżki — pliki zostają na swoim miejscu.",
    foldersTitle: "Foldery z muzyką",
    foldersHint: "Usunięcie folderu zabiera z biblioteki także jego utwory.",
    foldersEmpty: "Nie wskazano jeszcze żadnego folderu.",
    addFolder: "Dodaj folder",
    removeFolder: "Usuń folder",
    scan: "Skanuj bibliotekę",
    scanRunning: "Skanowanie…",
    statsFolders: "Foldery",
    statsTracks: "Utwory",
    progressFolder: "folder",
    progressFiles: "plików",
    progressIndexed: "dodanych",
    progressSkipped: "pominiętych",
    searchLabel: "Szukaj w bibliotece",
    searchPlaceholder: "Tytuł albo wykonawca…",
    searchEmpty: "Nic nie pasuje do tego wyszukiwania.",
    libraryEmpty: "Biblioteka jest pusta — dodaj folder z muzyką i uruchom skanowanie.",
    unknownArtist: "Nieznany wykonawca",
    unknownAlbum: "bez albumu",
    noDuration: "—",
    loadError: "Nie udało się wczytać biblioteki:",
    addError: "Nie udało się dodać folderu:",
    removeError: "Nie udało się usunąć folderu:",
    scanError: "Nie udało się uruchomić skanowania:",
    searchError: "Nie udało się wyszukać:",
  },
  footer: {
    version: "Wersja",
    protocol: "Protokół",
    db: "Baza",
    logs: "Logi",
  },
} as const;
