/**
 * Wszystkie teksty interfejsu DJ-a. Żaden tekst nie jest wpisany na sztywno w komponencie
 * (AGENTS.md, konwencje frontendu). Aplikacja jest po polsku.
 */
export const ui = {
  appName: "ANON DJ",
  window: {
    minimize: "Zminimalizuj",
    close: "Zamknij",
  },
  status: {
    player: "Odtwarzacz",
    playerUnknown: "nie sprawdzono",
    kiosk: "Kiosk",
    kioskDisconnected: "rozłączony",
    server: "Serwer",
    serverUnavailable: "nie nasłuchuje",
    serverUnknownAddress: "adres nieznany",
    loading: "Wczytywanie…",
    errorPrefix: "Błąd",
  },
  requests: {
    loadError: "Nie udało się wczytać kolejki:",
  },
  queue: {
    reviewTitle: "Do przeglądu",
    reviewHint: "Dedykacje od gości. Zatwierdzanie, edycja i wykonanie dochodzą w kolejnym etapie.",
    reviewEmpty: "Brak dedykacji czekających na przegląd.",
    readyTitle: "Gotowe do wykonania",
    readyHint: "Zatwierdzone dedykacje z gotowym głosem.",
    readyEmpty: "Nic nie czeka na wykonanie.",
    historyTitle: "Historia",
    historyHint: "Wykonane i odrzucone dedykacje.",
    historyEmpty: "Historia jest pusta.",
  },
  nav: {
    queues: "Kolejki",
    library: "Biblioteka",
    settings: "Ustawienia",
  },
  settings: {
    title: "Ustawienia",
    hint: "Wszystkie wartości zapisują się w bazie i obowiązują od razu po zapisaniu.",
    pinLabel: "PIN parowania kiosku",
    pinHint: "Dokładnie sześć cyfr. Kiosk podaje ten kod przy łączeniu.",
    portLabel: "Port serwera kiosków",
    portHint: "Ten sam port wpisujesz w kiosku — razem z adresem z paska statusu.",
    dedicationLimitLabel: "Limit dedykacji (znaki)",
    dedicationLimitHint: "Ile znaków może wpisać gość. Ten sam limit dostaje kiosk przy parowaniu.",
    guestNameLimitLabel: "Limit imienia gościa (znaki)",
    guestNameLimitHint: "Zero wyłącza pole imienia.",
    searchQueryLimitLabel: "Limit wyszukiwania (znaki)",
    save: "Zapisz",
    saving: "Zapisywanie…",
    saved: "Zapisano",
    loadError: "Nie udało się wczytać ustawień.",
    numberError: "Podaj poprawną liczbę.",
    portError: "Port musi być liczbą z zakresu 1024–65535.",
  },
  library: {
    title: "Biblioteka",
    hint: "Wskaż foldery z muzyką i uruchom skanowanie. Zapisujemy tylko metadane i ścieżki — pliki zostają na swoim miejscu.",
    foldersTitle: "Foldery z muzyką",
    foldersHint: "Usunięcie folderu zabiera z biblioteki także jego utwory.",
    foldersEmpty: "Nie wskazano jeszcze żadnego folderu.",
    addFolder: "Dodaj folder",
    removeFolder: "Usuń folder",
    scan: "Skanuj bibliotekę",
    scanRunning: "Skanowanie…",
    statsFolders: "Foldery",
    statsTracks: "Utwory",
    progressFolder: "folder",
    progressFiles: "plików",
    progressIndexed: "dodanych",
    progressSkipped: "pominiętych",
    searchLabel: "Szukaj w bibliotece",
    searchPlaceholder: "Tytuł albo wykonawca…",
    searchEmpty: "Nic nie pasuje do tego wyszukiwania.",
    libraryEmpty: "Biblioteka jest pusta — dodaj folder z muzyką i uruchom skanowanie.",
    unknownArtist: "Nieznany wykonawca",
    unknownAlbum: "bez albumu",
    noDuration: "—",
    loadError: "Nie udało się wczytać biblioteki:",
    addError: "Nie udało się dodać folderu:",
    removeError: "Nie udało się usunąć folderu:",
    scanError: "Nie udało się uruchomić skanowania:",
    searchError: "Nie udało się wyszukać:",
  },
  footer: {
    version: "Wersja",
    protocol: "Protokół",
    db: "Baza",
    logs: "Logi",
  },
} as const;
